name: Publish to PyPI (uv)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write   # for PyPI Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python (use .python-version if present or requires-python)
        run: uv python install

      - name: Sync (install) project
        run: uv sync --dev --locked || uv sync --dev

      - name: Run tests
        run: uv run pytest -q

      - name: Build sdist and wheel
        run: uv build --no-sources

      - name: Publish to PyPI with Trusted Publishing
        run: uv publish
